import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import VitaminD from "../public/assets/VITAMIND1.png";
import TitlePrice from "../components/TitlePrice";
import ShotDescription from "../components/ShotDescription";
import PriceInfo from "../components/PriceInfo";
import Footer from "../components/Footer";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Sample page</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			

			<section>
				<div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
					<div className={styles.left_col_width}>
						<Image
							src={VitaminD}
							width={370}
							height={370}
							alt='vitamin d'
						/>
						<div className='flex flex-row gap-6 mt-5'>
							<p className='font-kern text-xs'>AIMSIR Studio</p>
							<p className='font-kern text-xs border-b border-black ml-auto'>
								buy
							</p>
							<p className='font-kern text-xs'>licence</p>
						</div>

						<div className='mt-12 mb-12'>
							<ShotDescription title='artwork DESCRIPTION'>
								Lorem ipsum dolor sit amet, consectetur
								adipiscing elit. Pharetra semper tempor libero
								dolor luctus. Adipiscing amet, quis enim,
								pellentesque in dolor.
							</ShotDescription>
						</div>

						<div>
							<ShotDescription title='curators'></ShotDescription>
							<p className="text-sm font-kern mt-4">Deux Facit</p>
							<p className="text-sm font-kern">Lor Ipsum Dolor</p>
						</div>
					</div>
					<div >
						<div className="pl-10">
						<TitlePrice />

						<div className='mt-8'>
							<ShotDescription title='NFT DETAILS'>
								Lorem ipsum dolor sit amet, consectetur
								adipiscing elit. Pharetra semper tempor libero
								dolor luctus. Adipiscing amet, quis enim,
								pellentesque in dolor.
							</ShotDescription>
						</div>

						<div className='mt-14'>
							<ShotDescription title='additional content'>
								Lorem ipsum dolor sit amet, consectetur
								adipiscing elit. Pharetra semper tempor libero
								dolor luctus. Adipiscing amet, quis enim,
								pellentesque in dolor.
							</ShotDescription>
						</div>
						</div>
            <div className="mt-20">
              <PriceInfo/>
            </div>
					</div>
				</div>
			</section>

			
		</div>
	);
}
